#' Inject MCAR Missingness Into Tasks
#'
#' @description
#' Applies Missing Completely At Random (MCAR) drops to each task and variable at a
#' fixed proportion.
#'
#' @param data List of task datasets.
#' @param where.missing Optional structure indicating which variables/columns are eligible.
#' @param prop.missing Numeric in \eqn{(0,1)}; proportion of entries set to \code{NA}.
#'
#' @return The modified \code{data} list with inserted \code{NA}s.
#'
#' @examples
#' \dontrun{
#' dat.miss <- mcar.sim(data, prop.missing = 0.2)
#' }
#' @export

mcar.sim <- function(data, where.missing = NULL, prop.missing){
  dat <- data
  for(i in 1:length(data)){
    n <- nrow(dat[[i]])
    eligible <- if (is.null(where.missing)) rep(TRUE, ncol(dat[[i]])) else colnames(dat[[i]]) %in% where.missing
    
    for(j in which(eligible)){
      idx <- sample.int(n, ceiling(prop.missing * n))
      dat[[i]][idx, j] <- NA
    }
    
  }
  dat
}

#' Simulate Missing at Random (MAR) Patterns Driven by a Covariate
#'
#' @description
#' Introduces MAR missingness across selected variables in a list of task datasets.
#' The missingness indicator for each target variable is generated by a logistic
#' model using a user-specified covariate. For categorical targets (factor/character
#' or with ≤5 unique non-missing levels), missing rows are sampled at the requested
#' rate while retaining dependence on the covariate via a fitted logistic model.
#'
#' @param data A \code{list} of task datasets. Each element is either a
#'   \code{data.frame}/tibble or a list containing a component named \code{"data"}
#'   that holds the \code{data.frame}. Column names should be consistent across tasks.
#' @param prop.missing Numeric in \eqn{(0,1)} giving the target marginal missingness
#'   proportion per annotated variable within each task. Default \code{0.2}.
#' @param covaraite Name (character scalar) of the covariate used to drive MAR
#'   probabilities. This column must exist in each task dataset.  \strong{Note:}
#'   the argument name is spelled \code{covaraite} in the current API for
#'   backward compatibility; consider renaming to \code{covariate} in future releases.
#' @param where.missing Character vector of column names to which missingness
#'   will be applied. Required; function stops if not provided.
#'
#' @details
#' For each task \eqn{i} and each target variable \eqn{j} named in
#' \code{where.missing}:
#' \enumerate{
#'   \item Build a preliminary empirical missingness indicator:
#'     \itemize{
#'       \item Continuous targets: mark the top \code{prop.missing} fraction
#'         of observations by the empirical quantile threshold
#'         \code{quantile(var_j, 1 - prop.missing)}.
#'       \item Categorical targets: sample \code{round(n * prop.missing)}
#'         indices uniformly.
#'     }
#'   \item Flip a small random subset of indicators (about \eqn{n/10} total across
#'     positive and negative sets) to avoid separation in the logistic fit.
#'   \item Fit \code{glm(miss ~ x, family = binomial)} where \code{x} is the
#'     specified covariate; use the fitted response probabilities to draw the final
#'     missingness \code{rbinom(n, 1, p_i)} and set \code{NA}s accordingly.
#' }
#'
#' If each task element has a \code{$data} component, it is used as the working
#' frame; otherwise the element itself is treated as the working frame.
#'
#' @return A \code{list} of task datasets with \code{NA}s inserted according to MAR.
#'   The structure mirrors the input: if input elements had \code{$data}, the returned
#'   elements are bare \code{data.frame}s for imputation downstream.
#'
#' @examples
#' \dontrun{
#' set.seed(123)
#' tasks <- list(
#'   A = data.frame(z = rnorm(200), y = rnorm(200), g = sample(0:1, 200, TRUE)),
#'   B = data.frame(z = rnorm(180), y = rnorm(180), g = sample(letters[1:3], 180, TRUE))
#' )
#' # Induce MAR missingness in y, driven by covariate "z"
#' tasks_mar <- mar.sim(tasks, prop.missing = 0.3, covaraite = "z", where.missing = "y")
#' sapply(tasks_mar, function(df) mean(is.na(df$y)))
#' }
#'
#' @seealso \code{\link{mcar.sim}} for MCAR injection, and higher-level imputation
#'   routines such as \code{\link{mtlmice}}.
#'
#' @importFrom stats glm predict rbinom quantile
#' @export
mar.sim <- function(data, prop.missing = 0.2, covaraite = NULL, where.missing = NULL) {
  if("data" %in% names(data[[1]])) {
    data <- lapply(data, function(x) x[["data"]])
    dat <- data
  }else {
    dat <- data
  }
  
  for (i in seq_along(dat)) {
    datai <- data[[i]]
    dati <- dat[[i]]
    n <- nrow(dati)
    
    if (!is.null(where.missing)) {
      missing.n <- colnames(datai) %in% where.missing
      
      for (j in seq_along(colnames(datai))) {
        if (missing.n[j]) {
          x <- unlist(datai[, covaraite])
          varj <- dati[, j]
          
          # Check if variable is categorical (factor or character)
          is_categorical <- is.factor(varj) || is.character(varj) || length(na.omit(unique(varj))) <= 5
          
          if (!is_categorical) {
            # Continuous variable missingness
            miss_ind_empi <- varj > quantile(varj, (1 - prop.missing), na.rm = TRUE)
          } else {
            # Categorical variable missingness
            # Sample randomly but still create dependence on the covariate
            samp_ind <- sample(seq_len(n), size = round(n * prop.missing))
            miss_ind_empi <- rep(FALSE, n)
            miss_ind_empi[samp_ind] <- TRUE
          }
          
          # Flip a small portion to avoid perfect separation
          miss_ind_1 <- which(miss_ind_empi)
          miss_ind_2 <- which(!miss_ind_empi)
          loc <- c(
            sample(miss_ind_1, min(length(miss_ind_1), ceiling(n / 20))),
            sample(miss_ind_2, min(length(miss_ind_2), ceiling(n / 20)))
          )
          miss_ind_empi[loc] <- 1 - miss_ind_empi[loc]
          
          # Fit logistic model on covariate
          miss_dat <- data.frame(x = x, miss = miss_ind_empi)
          fit <- glm(miss ~ x, data = miss_dat, family = binomial)
          miss_prob_real <- predict(fit, type = "response")
          
          # Introduce missingness
          dati[rbinom(n, 1, miss_prob_real) == 1, j] <- NA
        }
      }
    } else {
      stop("Please provide the variables to have missing values using 'where.missing'")
    }
    
    dat[[i]] <- dati
  }
  
  return(dat)
}
